import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/nav/Nav'
import styles from '../styles/Home.module.scss'
import requests from '../utils/requests'

export default function Home({ results }) {
  console.log(results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  try {
    const response = await axios.get(`https://api.themoviedb.org/3${requests[genre]?.url || requests.trending.url}`)
    return {
      props: {
        results: response.data.results
      }
    }
  } catch (err) {
    console.log(err);
  }
}